<section>
    <h1>Catégories</h1>
    <ul>
        <ul>
            <h2>Cinéma<a href="">+</a></h2>
            <li><a href="">Aventure</a></li>
        </ul>
        <ul>
            <h2>Jeux vidéos<a href="">+</a></h2>
            <li><a href="">Aventure</a></li>
        </ul>
        <ul>
            <h2>Cinéma<a href="">+</a></h2>
            <li><a href="">Zelda</a></li>
        </ul>
        <ul>
            <h2>Littérature<a href="">+</a></h2>
            <li><a href="">Zelda</a></li>
        </ul>
        <ul>
            <h2>Maquillage</h2>
        </ul>
    </ul>
</section>