<section>
    <h1>Catégories<a href="index.php?route=create-category">+</a> </h1>
    <ul>
        <ul>
            <?php foreach ($categories as $category) {?>
            <h2><?= $category->getCategoryName();?></h2><a href="index.php?route=create-channel">+</a><?php
            }
        ?>
                <?php foreach ($channels as $channel){ ?>
                <li><?= $channel->getChannelName(); ?></li><?php
}
        ?>
        </ul>
    </ul>
</section>